
import ContainerCenterComponent from './components/container-center/container';
import ArticleComponent from './components/article/article';
import HelperComponent from './components/helper/helper';


function App() {
  return (
    <div className="App">
    	<ContainerCenterComponent />
    	<ArticleComponent heading="Ufo exist or don't exist?" articleText = "Are we alone in this universe? This is a question that undoubtedly passes through every mind several times during a lifetime. We often hear a lot of stories about close encounters, Unidentified Flying Objects(UFO) sightings and other mysterious things, but we lack documented evidence for analysis of this topic. The objective of this paper is to analyze one database which has a collection of documented reports of UFO sightings to uncover any fascinating story related to the data. Using SAS® Enterprise Miner TM 13.1, the powerful capabilities of text analytics and topic mining are leveraged to summarize the associations between various reported sightings. We have also used PROC GEOCODE to convert addresses of sightings to the locations on the map and then used PROC GMAP procedure to produce block map to represent the frequency of the sightings in various locations. Our preliminary analysis of the data associated with sightings, it was found that the most popular words associated with UFOs tell us about their shapes, formations, movements and colors. The Text Profiler node available in SAS® Enterprise Miner TM 13.1 is leveraged to build model and cluster the data into different levels of segment variable. We also explain how the opinions of the UFO sightings changes over a period of time using Text Profiling. Further, this Analysis is used to find interesting terms or topics and model using Text Profile node to describe the UFO Sightings." />
    	<ArticleComponent className="article-error" heading="Mars Attacks!" articleText="Mars Attacks! is uncommon for intuiting this technological one-sidedness. In it, humans are not a threat to the Martians. Our nuclear weapons have no effect on them; in fact, they are redirected to comic purposes. Meanwhile, we are powerless against their ray guns. The Martians aren’t really here to destroy us or enslave us or steal our resources. We are nothing but a source of cruel, absurd amusement to them. The movie starts with a stampede of cattle on fire and includes scenes with Martians toppling the Easter Island statues like bowling pins and a flying saucer tipping over the Washington Monument in such a way as to fall on a troop of Boy Scouts (somehow still on a field trip during an alien invasion). The Martians delight in seeing how many times they can brazenly lie to us and still get us to be willing victims. Their experiments seem designed for maximum absurdity, such as sewing Sarah Jessica Parker’s head onto the body of a Chihuahua, simply because they can. This is Tim Burton showing off his weirdness and creativity, but in the process Mars Attacks! provides a rare answer to the question of why aliens are on Earth: to goof on us. And kill us. Both, really. It’s a theme rarely explored in alien movies. Even in Predator, the aliens hunt humans precisely because we are to be taken seriously. It’s a much more nihilistic premise than that of Independence Day, but it’s also a lot more realistic than the idea that alien invaders hadn’t upgraded their anti-virus software. Really, why else would they land here?" />
    	<ArticleComponent className="article-success" heading="Song Machine, Season One: Strange Timez" articleText="Song Machine, Season One: Strange Timez is the seventh studio album by British virtual band Gorillaz, released on 23 October 2020. The album is released as part of Gorillaz' Song Machine project, a web series consisting of a collection of singles and music videos, dubbed 'episodes' each featuring different guest artists. The album marked the return of the character Murdoc Niccals in promotional material, after his absence from The Now Now in 2018. The record received widespread critical acclaim from music critics." />
   		<HelperComponent text="need help with this" />
    </div>
  );
}

export default App;
